//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamSubject
    {
        public long Id { get; set; }
        public Nullable<long> ExamId { get; set; }
        public Nullable<long> SubjectId { get; set; }
    }
}
