//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mcq
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mcq()
        {
            this.Submissions = new HashSet<Submission>();
        }
    
        public long Id { get; set; }
        public Nullable<long> SubjectId { get; set; }
        public Nullable<long> ChapterId { get; set; }
        public Nullable<long> ExamId { get; set; }
        public string Question { get; set; }
        public string OptionA { get; set; }
        public string OptionB { get; set; }
        public string OptionC { get; set; }
        public string OptionD { get; set; }
        public string CorrectOption { get; set; }
        public Nullable<long> UpVotes { get; set; }
        public Nullable<long> DownVotes { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    
        public virtual Chapter Chapter { get; set; }
        public virtual Exam Exam { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Submission> Submissions { get; set; }
    }
}
